### ISSUE TITLE
setting the user/pwd

### ISSUE THREAD

**Issue by yogeshVU** [ZhuangweiKang/RESTfulSwarmLM#1]
usr='admin', pwd='kzw', address='127.0.0.1', port='27017'

**Comment by yogeshVU** [comment]
also updating the docs

**Comment by ZhuangweiKang** [comment]
`
# install mongodb
./dependences.sh DB $usr $pwd $db
# add user
mongo < initdb.js
# configure db to allow remote access
mv ./mongod.conf /etc/mongod.conf
systemctl restart mongod
systemctl status mongod
`

**Comment by ZhuangweiKang** [comment]
I write db info into a indepedent file DBinfo.json that is used for all other actors who need database connection information.
Directly adding db user in shell script doesn't work even for same commands, but I don't know the exact reason.
