### ISSUE TITLE
check docker experimental dependencies

### ISSUE THREAD

**Issue by yogeshVU** [ZhuangweiKang/RESTfulSwarmLM#2]
https://github.com/ZhuangweiKang/RESTfulSwarm/blob/master/dependences.sh#L31

**Comment by ZhuangweiKang** [comment]
# check docker experimental feature
    docker_version=$(docker version -f '{{.Server.Experimental}}')

    if [ "$docker_version" = "false" ];
    then
        echo "{\"experimental\": true}" > /etc/docker/daemon.json
        # restart docker daemon
        systemctl restart docker
        systemctl daemon-reload
    fi

    echo $(docker version)
